// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBYd5lheuZXvHxwz05mkw1rQUgXTYWojw',
    appId: '1:351935273736:web:b6cabd18da02c262066abd',
    messagingSenderId: '351935273736',
    projectId: 'collab-de419',
    authDomain: 'collab-de419.firebaseapp.com',
    storageBucket: 'collab-de419.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE-vmWGIx2hqI3GazImJoRW9q-5FtzJW4',
    appId: '1:351935273736:android:022c58ddaf0b3c78066abd',
    messagingSenderId: '351935273736',
    projectId: 'collab-de419',
    storageBucket: 'collab-de419.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbm9-zIofNjgaKEZccbFc9DyyxvZluYQ8',
    appId: '1:351935273736:ios:4f10ab438a4227d0066abd',
    messagingSenderId: '351935273736',
    projectId: 'collab-de419',
    storageBucket: 'collab-de419.firebasestorage.app',
    iosBundleId: 'com.example.collab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbm9-zIofNjgaKEZccbFc9DyyxvZluYQ8',
    appId: '1:351935273736:ios:4f10ab438a4227d0066abd',
    messagingSenderId: '351935273736',
    projectId: 'collab-de419',
    storageBucket: 'collab-de419.firebasestorage.app',
    iosBundleId: 'com.example.collab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBYd5lheuZXvHxwz05mkw1rQUgXTYWojw',
    appId: '1:351935273736:web:b2a7f45d5d809a37066abd',
    messagingSenderId: '351935273736',
    projectId: 'collab-de419',
    authDomain: 'collab-de419.firebaseapp.com',
    storageBucket: 'collab-de419.firebasestorage.app',
  );

}